# Generated by Django 5.0 on 2025-11-01 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trainers', models.ManyToManyField(limit_choices_to={'role': 'TRAINER'}, related_name='courses_trained', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
